-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 18:08:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dev-portal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dev-portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev-portal` DEFAULT CHARACTER SET utf8 ;
USE `dev-portal` ;

-- -----------------------------------------------------
-- Table `dev-portal`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`user` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NULL,
  `last_login` TIMESTAMP NOT NULL,
  `role_id` ENUM('user', 'moderator', 'admin') NOT NULL,
  `active` TINYINT NOT NULL,
  `version` INT NOT NULL,
  `salt` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`technology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`technology` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`technology` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_technology_technology_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_technology_technology`
    FOREIGN KEY (`parent_id`)
    REFERENCES `dev-portal`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`user_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`user_skill` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`user_skill` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `technology_id` BIGINT(20) NOT NULL,
  `knowledge_level` INT NOT NULL,
  `is_mentor` TINYINT NOT NULL,
  INDEX `fk_user_skill_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_skill_technology1_idx` (`technology_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `technology_id`),
  CONSTRAINT `fk_user_skill_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_skill_technology1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `dev-portal`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`post_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`post_comment` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`post_comment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `post_id` BIGINT(20) NOT NULL,
  `post_comment_id` BIGINT(20) NULL,
  `author_id` BIGINT(20) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` TIMESTAMP NULL,
  `comment` TEXT NOT NULL,
  `verison` INT NOT NULL,
  `comment_type` ENUM('comment', 'answer') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_post_comment_post_comment1_idx` (`post_comment_id` ASC) VISIBLE,
  INDEX `fk_post_comment_user1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dev-portal`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_post_comment1`
    FOREIGN KEY (`post_comment_id`)
    REFERENCES `dev-portal`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`post` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`post` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `solution_id` BIGINT(20) NULL,
  `author_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(70) NULL,
  `slug` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NULL,
  `post_content` JSON NOT NULL,
  `status` ENUM('solved', 'unsolved', 'open', 'deleted') NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_post_comment1_idx` (`solution_id` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_post_comment1`
    FOREIGN KEY (`solution_id`)
    REFERENCES `dev-portal`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`notifications` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`notifications` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `from_id` BIGINT(20) NOT NULL,
  `url` VARCHAR(45) NULL,
  `type` ENUM('like', 'comment', 'answer') NULL,
  `note` TEXT NULL,
  `status` ENUM('new', 'viewed', 'important') NOT NULL,
  `post_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_notifications_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_notifications_user2_idx` (`from_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dev-portal`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_user2`
    FOREIGN KEY (`from_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `dev-portal`.`votes_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`votes_comment` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`votes_comment` (
  `user_id` BIGINT(20) NOT NULL,
  `post_comment_id` BIGINT(20) NOT NULL,
  `vote` TINYINT NOT NULL,
  INDEX `fk_votes_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_votes_comment_post_comment1_idx` (`post_comment_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `post_comment_id`),
  CONSTRAINT `fk_votes_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_comment_post_comment1`
    FOREIGN KEY (`post_comment_id`)
    REFERENCES `dev-portal`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`votes_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`votes_post` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`votes_post` (
  `user_id` BIGINT(20) NOT NULL,
  `post_id` BIGINT(20) NOT NULL,
  `vote` TINYINT NOT NULL,
  INDEX `fk_votes_post_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_votes_post_post1_idx` (`post_id` ASC) VISIBLE,
  PRIMARY KEY (`post_id`, `user_id`),
  CONSTRAINT `fk_votes_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dev-portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_post_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dev-portal`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev-portal`.`post_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev-portal`.`post_tag` ;

CREATE TABLE IF NOT EXISTS `dev-portal`.`post_tag` (
  `technology_id` BIGINT(20) NOT NULL,
  `post_id` BIGINT(20) NOT NULL,
  INDEX `fk_table3_technology1_idx` (`technology_id` ASC) VISIBLE,
  INDEX `fk_table3_post1_idx` (`post_id` ASC) VISIBLE,
  PRIMARY KEY (`technology_id`, `post_id`),
  CONSTRAINT `fk_table3_technology1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `dev-portal`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table3_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dev-portal`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `user` VALUES 
  -- id email password first_name last_name middle_name phone_number, created, updated, last_login, role_id, active, version, salt--
	(1,'braeden.norman6@gmail.com', '1afb87f97a4cc4e79fa9f7a0ce295836f6695be3cf9044abc611083cd4fe5a0e', 'Braeden', 'Norman',null, '16046667777', current_timestamp(),null,current_timestamp(), 'admin',1, 0, "243262243132244e79524748346744576a5436414e72387271714e7375" );
    
INSERT INTO `post` VALUES 
  -- id solution_id author_id title description slug created updated post_content status, version--
	(1,null,1, 'how to install python', null, 'how-to-install-python', current_timestamp(), null, '[{"url": "https://i.imgur.com/3GmPd7O.png", "type": "image"}, {"text": "How do I install python?", "type": "text"}]', 'unsolved', 0);

INSERT INTO `technology` VALUES
	(1,"Java", null),
	(2,"JavaScript", null),
	(3,"Spring", 1),
	(4,"NodeJS", 2),
    (5,"Python", null),
    (6,"VSCode", null),
    (7,"ExpressJS", 4);

INSERT INTO `post_tag` VALUES
	(5,1),
	(6,1);
    
INSERT INTO `post_comment` VALUES
	-- id post_id post_comment_id author_id created updated commment version comment_type --
	(1,1,null,1, current_timestamp(), null, "answer 1", 0, 'answer'),
    (2,1,1,1, current_timestamp(), null, "comment 1 on answer 1", 0, 'comment'),
    (3,1,null,1, current_timestamp(), null, "comment 1", 0, 'comment'),
    (4,1,null,1, current_timestamp(), null, "answer 2", 0, 'answer'),
    (5,1,1,1, current_timestamp(), null, "comment 2 on answer 1", 0, 'comment'),
    (6,1,1,1, current_timestamp(), null, "comment 3 on answer 1", 0, 'comment'),
    (7,1,1,1, current_timestamp(), null, "comment 4 on answer 1", 0, 'comment'),
    (8,1,null,1, current_timestamp(), null, "comment 2", 0, 'comment');
    

INSERT INTO `votes_post` VALUES
	(1,1,true);


INSERT INTO `votes_comment` VALUES
	(1,1,false);
